from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from pl_farmers_market.config.ConfigStore import *
from pl_farmers_market.udfs.UDFs import *

def create_Col_Source(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("FMID"), 
        col("MarketName"), 
        col("Website"), 
        col("Facebook"), 
        col("Twitter"), 
        col("Youtube"), 
        col("OtherMedia"), 
        concat_ws(
            "", 
            coalesce(col("Website"), lit("")), 
            coalesce(col("Facebook"), lit("")), 
            coalesce(col("Twitter"), lit("")), 
            coalesce(col("Youtube"), lit("")), 
            coalesce(col("OtherMedia"), lit(""))
          )\
          .alias("Source"), 
        col("street"), 
        col("city"), 
        col("County"), 
        col("State"), 
        col("zip"), 
        col("Season1Date"), 
        col("FromDate").cast(DateType()).alias("FromDate"), 
        col("ToDate").cast(DateType()).alias("ToDate"), 
        col("Season1Time"), 
        col("Season2Date"), 
        col("Season2Time"), 
        col("Season3Date"), 
        col("Season3Time"), 
        col("Season4Date"), 
        col("Season4Time"), 
        col("x"), 
        col("y"), 
        col("Location"), 
        col("Credit"), 
        col("WIC"), 
        col("WICcash"), 
        col("SFMNP"), 
        col("SNAP"), 
        col("Organic"), 
        col("Bakedgoods"), 
        col("Cheese"), 
        col("Crafts"), 
        col("Flowers"), 
        col("Eggs"), 
        col("Seafood"), 
        col("Herbs"), 
        col("Vegetables"), 
        col("Honey"), 
        col("Jams"), 
        col("Maple"), 
        col("Meat"), 
        col("Nursery"), 
        col("Nuts"), 
        col("Plants"), 
        col("Poultry"), 
        col("Prepared"), 
        col("Soap"), 
        col("Trees"), 
        col("Wine"), 
        col("Coffee"), 
        col("Beans"), 
        col("Fruits"), 
        col("Grains"), 
        col("Juices"), 
        col("Mushrooms"), 
        col("PetFood"), 
        col("Tofu"), 
        col("WildHarvested"), 
        col("updateTime")
    )
